sudo: false

env:
  - PLATFORM=x86_64 WINE=wine64 UNICODE=
  - PLATFORM=i686 WINE=wine UNICODE=
  - PLATFORM=x86_64 WINE=wine64 UNICODE=1
  - PLATFORM=i686 WINE=wine UNICODE=1

language: cpp

cache:
  - apt
  - ccache

addons:
  apt:
    packages:
    - binutils-mingw-w64-i686
    - binutils-mingw-w64-x86-64
    - mingw-w64-dev
    - g++-mingw-w64-i686
    - g++-mingw-w64-x86-64
    - gcc-mingw-w64-i686
    - gcc-mingw-w64-x86-64
    - wine

script:
  - make PLATFORM=$PLATFORM UNICODE=$UNICODE
  - make test PLATFORM=$PLATFORM UNICODE=$UNICODE
  - cd example/DllLoader
  - WINEPREFIX=`pwd`/$WINE WINEPATH=/usr/lib/gcc/$PLATFORM-w64-mingw32/4.6/ $WINE ./DllLoader.exe
  - WINEPREFIX=`pwd`/$WINE WINEPATH=/usr/lib/gcc/$PLATFORM-w64-mingw32/4.6/ $WINE ./DllLoaderLoader.exe
